require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fire_departments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FireDepartment. As you add validations to FireDepartment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FireDepartment.create! valid_attributes
      get fire_departments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fire_department = FireDepartment.create! valid_attributes
      get fire_department_url(fire_department)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fire_department_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      fire_department = FireDepartment.create! valid_attributes
      get edit_fire_department_url(fire_department)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FireDepartment" do
        expect {
          post fire_departments_url, params: { fire_department: valid_attributes }
        }.to change(FireDepartment, :count).by(1)
      end

      it "redirects to the created fire_department" do
        post fire_departments_url, params: { fire_department: valid_attributes }
        expect(response).to redirect_to(fire_department_url(FireDepartment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FireDepartment" do
        expect {
          post fire_departments_url, params: { fire_department: invalid_attributes }
        }.to change(FireDepartment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post fire_departments_url, params: { fire_department: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fire_department" do
        fire_department = FireDepartment.create! valid_attributes
        patch fire_department_url(fire_department), params: { fire_department: new_attributes }
        fire_department.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fire_department" do
        fire_department = FireDepartment.create! valid_attributes
        patch fire_department_url(fire_department), params: { fire_department: new_attributes }
        fire_department.reload
        expect(response).to redirect_to(fire_department_url(fire_department))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        fire_department = FireDepartment.create! valid_attributes
        patch fire_department_url(fire_department), params: { fire_department: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fire_department" do
      fire_department = FireDepartment.create! valid_attributes
      expect {
        delete fire_department_url(fire_department)
      }.to change(FireDepartment, :count).by(-1)
    end

    it "redirects to the fire_departments list" do
      fire_department = FireDepartment.create! valid_attributes
      delete fire_department_url(fire_department)
      expect(response).to redirect_to(fire_departments_url)
    end
  end
end
